[package]
name = "pong_wars"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
gloo = "0.11.0"
rand = "0.8.5"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "HtmlCanvasElement",
  "CanvasRenderingContext2d"
]
